### ISSUE TITLE
gradle sync failed

### ISSUE THREAD

**Issue by rohansood42** [glomadrian/material-animated-switch#16]
tried both the inclusions
<img>![capture](https://cloud.githubusercontent.com/assets/17768786/14413402/6245de10-ff96-11e5-9ee0-c3accaf74347.PNG)</img>

**Comment by lightzero** [comment]
add 
maven {
    url "http://dl.bintray.com/glomadrian/maven"
  }

in build.gradle (project)--> allprojects-->repositories
