### ISSUE TITLE
setChecked()

### ISSUE THREAD

**Issue by FateLight** [glomadrian/material-animated-switch#17]

**Comment by macdonaldj** [comment]
is there a way to set it checked by default? can't toggle in adapter in bindview. causes null pointer on animator

**Comment by macdonaldj** [comment]
answered from another issue:

togglebtn.post(new Runnable() {
    @Override
    public void run() {
     togglebtn.toggle();
    }
});

**Comment by liangbaochang** [comment]
Thank you！
