### ISSUE TITLE
Gradle Sync fail

### ISSUE THREAD

**Issue by GYberkeley** [glomadrian/material-animated-switch#9]
![image](https://cloud.githubusercontent.com/assets/5403938/8813229/a0dc70cc-2fb6-11e5-91c0-62ef20a87f0a.png)

**Comment by GYberkeley** [comment]
Fixed the issue and it was not glomadrian's fault

**Comment by jssisodiya** [comment]
@GYberkeley what was the issue, I am also getting the same error
